### ISSUE TITLE
Error: collection-repeat expected attribute collection-item-height to be a an expression that returns a number (in pixels) or percentage.

### ISSUE THREAD

**Issue by benag** [guylabs/ion-autocomplete#64]
I Am geting an error:
Error: collection-repeat expected attribute collection-item-height to be a an expression that returns a number (in pixels) or percentage.
    at link (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:40800:15)
    at nodeLinkFn (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:14336:13)
    at compositeLinkFn (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:13730:13)
    at compositeLinkFn (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:13733:13)
    at nodeLinkFn (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:14330:24)
    at compositeLinkFn (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:13730:13)
    at compositeLinkFn (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:13733:13)
    at nodeLinkFn (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:14330:24)
    at compositeLinkFn (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:13730:13)
    at compositeLinkFn (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:13733:13)

**Comment by guylabs** [comment]
Hi,

there was already a similar issue: #21. What kind of Ionic version do you use? And what kind of `ion-autocomplete` version do you use? You need to have the matching Ionic version. See the table here and adapt your Ionic or the `ion-autocomplete` version: https://github.com/guylabs/ion-autocomplete#ionic-compatibility

When you have the proper version this issue should be gone. Can you please verify and then come back to me such that I can close the issue?

Thanks and regards,

Guy

**Comment by benag** [comment]
1.0.0-beta.13
is not on the list...

**Comment by guylabs** [comment]
Then you will need to update the Ionic version as this component is done for `1.0.0-beta.14` and upwards and there are no plans to support older versions than `beta.14`.

What kind of `ion-autocomplete` version are you using? And could you update to the according Ionic version and try again?

**Comment by benag** [comment]
I updated to beta14 and used 0.2.2 fix most issues but now itemsClick is not being called...

**Comment by benag** [comment]
updated to beta 14 using 0.1.2 now my issue is that the items-clicked-method is not being called, maybe i will try another version?

**Comment by benag** [comment]
now i have a problem that ng-model is not set...

**Comment by guylabs** [comment]
what do you mean the `ng-model` is not set? Maybe you could right away update to the 1.0.0 Ionic version and then use the 0.2.3 version of the component where you have some more features etc.

**Comment by guylabs** [comment]
Hi, 

are there any news on this? You can also try to update to the `0.3.0` version as there Ionic 1.1.0 is used with Angular 1.4.3. You can always reopen the issue if there is something more.

Thanks and regards,

Guy
